### DISCUSSION TITLE
Images with different widths

### DISCUSSION THREAD

**Discussion by gbgr1979** [fancyapps/ui#182] [Q&A]
Hi,

My carousel is loaded with images that have different widths but this leaves a large gap in between images because the carousel__slide class has a fixed with.

Does anyone know a way around this?

**Comment by fancyapps** [comment]
Hi,

The simplest solution would be to use CSS to fill slides with image, something like this:

```css
img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
```
You could also set different width for each slide element (using CSS).
