### DISCUSSION TITLE
Carousel adapt to mobile phone

### DISCUSSION THREAD

**Discussion by colormango** [fancyapps/ui#232] [Q&A] [answered]
I made a Carousel example:
[https://www.colormango.com/test/carousel.html](https://www.colormango.com/test/carousel.html)
Displays fine on desktop
But it is not suitable for mobile device
Is it possible to display only 1 picture each time on the mobile, just like a slider?

**Comment by fancyapps** [comment, marked as answer]
Hi,

Please explain what you mean by "it is not suitable for mobile device". 

Use CSS to control the number of visible slides, example:

```css
  /* One slide visible by default */
  .carousel__slide {
    width: 100%;
  }

  /* Two slides visible on larger screens (or 3 if the number of slides is odd and the last slide is centered) */
  @media (min-width: 800px) {
    .carousel__slide {
      width: 50%;
    }
  }
```
