### DISCUSSION TITLE
I would like video iframe take max screen size as possible

### DISCUSSION THREAD

**Discussion by GabrielTavernier** [fancyapps/ui#460] [Q&A]
Hy, 
When I use fancybox 5 with youtube video iframe the size of the container is limited to 960px width and 540 px height even if my window is bigger !
I would like it can be bigger as possible (only limited by the window size).

Is it possible with option ?

**Comment by fancyapps** [comment]
Hi,

You can customize dimension using CSS, like this:

```css
.has-youtube .fancybox__content,
.has-vimeo .fancybox__content,
.has-html5video .fancybox__content {
  width: 100%;
  height: 100%;
}
```

Keep in mind that the scrip will adjust width/height to match aspect ratio, if you wish, you can disable that (or set another aspect ratio), like this:

```js
Fancybox.bind("[data-fancybox]", {
  Html: {
    videoRatio: false,
  },
});
```
