### DISCUSSION TITLE
Some old reset CSS messes up the behavior of Fancybox and Carousel a lot.

### DISCUSSION THREAD

**Discussion by btrazzini** [fancyapps/ui#526] [Q&A]
Unfortunately there are still sites with css reset and when I try to use Facybox or Carousel some divs do not appear. For example the second slide or the dots

```css
/* ----- reset html5doctor ----- */
html,body,div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,
address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,
b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,
thead,tr,th,td,article,aside,canvas,details,figcaption,figure,footer,header,
hgroup,menu,nav,section,summary,time,mark,audio,video,a{background-color:transparent; background-repeat:no-repeat; box-sizing:border-box; border:0; font-size:100%; line-height:1.2em; margin:0; outline:0; padding:0; vertical-align:top;}

div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,
address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,
b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,
thead,tr,th,td,article,aside,canvas,details,figcaption,figure,footer,header,
hgroup,menu,nav,section,summary,time,mark,audio,video,a{overflow:hidden;}
```
