### DISCUSSION TITLE
Left Align Caption When Lightbox Is Open

### DISCUSSION THREAD

**Discussion by manek43509** [fancyapps/ui#718] [General]
I am trying to align the caption which displays when the lightbox opens and the image displays large. I have added CSS using the attribute `.fancybox__caption` and I know this is the right class to use because other changes I have made (ie. font size and weight) display correctly, but `.fancybox__caption { text-align: left; }` does nothing. Any ideas why this is?

**Comment by fancyapps** [comment]
Hi,

Here is one possible solution:

```css
.fancybox__caption {
  margin-right: auto;
}
```

https://jsfiddle.net/c7gh48q9/

Another option would be to make it 100% wide:

```css
.fancybox__caption {
   width: 100%;
}
```

https://jsfiddle.net/a3u8xLbn/
