### ISSUE TITLE
Multi-line caption not centered 

### ISSUE THREAD

**Issue by stathimexas** [fancyapps/ui#161]
When the caption is multi-lined via a `<br>,` the text is not centered.

**Comment by fancyapps** [comment]
Hi,

To align text horizontally, use CSS:

```CSS
.fancybox__caption {
    text-align: center;
}
```
