### ISSUE TITLE
Suggested changes to SCSS (non-breaking)

### ISSUE THREAD

**Issue by AndersMad** [fancyapps/ui#248]
Hi, these are changes I merge in after updates - I'd love for them to be a part of std. - they are all non-breaking / full backwards compat.

### FIX 1: Do not add margin if dots are overlaid/inside just by an @if wrap
**OLD:** in /Carousel/plugins/Dots/Dots.scss @ line 1
```scss
.has-dots { 
    margin-bottom: ... 
```
**NEW:**
```scss
.has-dots { 
    @if ($carousel-dots-margin > 0) { 
        margin-bottom: ...
    }
}
```

### FIX 2: Make the border radius configurable so it can be a flat square etc.
**OLD:** in /Carousel/plugins/Dots/Dots.scss @ line 38
```scss
border-radius: 50%;
```
**NEW:**
```scss
border-radius: $carousel-dots-dot-radius;
```
**ADD:** in /Carousel/scss/_variables.scss
```scss
$carousel-dots-dot-radius: 50% !default;
```

### FIX 3: Responsiveness needs width to go away so simply wrap with an @if
**OLD:** in /Carousel/scss/base.scss @ line 35
```scss
width: $carousel-slide-width;
```
**NEW:**
```scss
@if ($carousel-slide-width) { width: $carousel-slide-width; }
```
.. then one can do `$carousel-slide-width: '';` to make BS5 work so it shows e.g. 3 slides on desktop but only 1 on mobile.
