### ISSUE TITLE
Plyr controls are dotted on focus

### ISSUE THREAD

**Issue by kgnfth** [fancyapps/ui#254]
When using `data-fancybox-plyr` the player controls are dotted when clicking buttons

![image](https://user-images.githubusercontent.com/73314940/156917504-95d69539-ea14-4093-8ab7-9be66764c381.png)

See: https://fancyapps.com/playground/vq

**Comment by fancyapps** [comment]
Hi,

You have to overwrite default outline set by Fancybox, for example:

```css
body.is-using-mouse .fancybox__content .plyr :focus {
  outline: none;
}
```
