### ISSUE TITLE
mainClass not getting added

### ISSUE THREAD

**Issue by ginagregory** [fancyapps/ui#26]
I'm trying to use the 'mainClass' option to add a custom class. I see in the code it's supposed to add to the .fancybox__carousel, but it is not getting added.

```
var popup = new Fancybox(
[
{
type: 'ajax',
src: '/?view=popup-email',
mainClass: 'email-popup'
}
],{
on: {
init: function(){},
reveal: function(){}
});
```

Am I doing something wrong here?

**Comment by fancyapps** [comment]
Hi,

Customizing the `mainClass` option for each slide is not supported, it can be defined as follows:

```CSS
var popup = new Fancybox(
  [
    {
      type: 'ajax',
      src: '?view=popup-email'
    }
  ],{
    mainClass: 'email-popup',
    on: {
      init: function(){},
      reveal: function(){}
    }
  }
);
```
