### ISSUE TITLE
how to make fancybox4 to show youtube video as in fancybox3 (like lamost all screen)?

### ISSUE THREAD

**Issue by AucT** [fancyapps/ui#273]
I'm using fancybox3 and it's great. 
I tried fancybox4 but youtube video iframe is very small. In fancybox3 it was almost whole screen.

How to set fancybox4 to behave as fancybox3? How to make it show youtube iframe almost like whole screen?

**Comment by fancyapps** [comment]
Hi,

Content (video) dimensions are controlled using CSS. Therese are default values:

```CSS
.fancybox__carousel .fancybox__slide.has-html5video .fancybox__content, 
.fancybox__carousel .fancybox__slide.has-video .fancybox__content {
    height: 540px;
    max-height: 100%;
    max-width: 100%;
    width: 960px;
}
```
