### ISSUE TITLE
How to hide cards that are not completely visible on Fancyapps carousel?

### ISSUE THREAD

**Issue by Mark-in-Motion** [fancyapps/ui#303]
Is it possible to make my carousel looks like the image attached where the next slide is completely hidden instead of showing just a section of it that makes it look like it's cut. 

I tried editing the` .carousel__track` to `overflow: hidden` but it made the other slides invisible. [You can look at this playground link](https://fancyapps.com/playground/2TG)

![carousel](https://user-images.githubusercontent.com/37282432/172116583-90ee0dcb-0fcb-4392-a6df-799f8699d15f.JPG)

**Comment by fancyapps** [comment]
Hi,

You can use `.is-selected` class name to target slides in the current page.

Example:

```css
.carousel__slide {
   opacity: 0;
   transition: opacity .5s ease;
}

.carousel__slide.is-selected {
   opacity: 1;
}
```

https://fancyapps.com/playground/2TI

OR you could just simply remove padding from `.carousel__viewport` element and next/prev slides would not be visibile.
