### ISSUE TITLE
How to fix header flicker when fancybox open/close? 

### ISSUE THREAD

**Issue by sonupandit** [fancyapps/ui#423]
In version 4.x.x we were using "compensate-for-scrollbar" class on the fixed element.

**Comment by fancyapps** [comment]
Hi,

You either use the same `compensate-for-scrollbar` class name or use `--fancybox-scrollbar-compensate` CSS variable. For example, project homepage uses this CSS snippet for header element:

```css
.VPNav {
    padding-right: var(--fancybox-scrollbar-compensate,0);
}
```

**Comment by trompx** [comment]
Hey, I already handle that myself because I use Lenis for smoothScroll. Is there a way to prevent fancybox to set that css var?

EDIT: did the following as workaround
```css
body.hide-scrollbar {
  margin-right: 0 !important;
}
```
