### ISSUE TITLE
Carousel Slides Per Page

### ISSUE THREAD

**Issue by dmitrue** [fancyapps/ui#478]
### Describe the bug

Hi, I'm following this guide [https://fancyapps.com/carousel/responsive-design/](url) and everything works fine when I have 3 slides per page `--f-carousel-slide-width: calc(100% / 3)`, however there some problems If I want  to set 4 slides per page `--f-carousel-slide-width: calc((100% - 16px) / 4)`, please see screenshot. I think this issue related to mine as well [https://github.com/fancyapps/ui/issues/477](url)

<img width="1404" alt="Screenshot 2023-04-12 at 13 34 38" src="https://user-images.githubusercontent.com/6647735/231371921-f341d9f1-5822-42d0-8234-22e41e6d8b79.png">

### Reproduction

Set to 4 or 5 etc.
--f-carousel-slide-width: calc((100% - 16px) / 4)

**Comment by fancyapps** [comment]
First, please, create a demo using jsfiddle or any other codeplayground demo.
Secondly, infinite navigation is automatically disabled if all pages are at least partially visible.

**Comment by dmitrue** [comment]
Hi, the issue is that it supposed to be 4 slides per page, not 3 and two half of other, like on screenshot

**Comment by dmitrue** [comment]
Here you go https://jsfiddle.net/4txur6m7/, I have 8 slides, but 3 pages for some reason. And, as I understand, should be 2 pages with 4 slides on each

**Comment by fancyapps** [comment]
Maybe documentation was not clear enough, you simply set slide count using CSS, e.g., make sure that slide width is really what you expect it to be.

Here is a simple example how to set fixed number of slides:

```css
#myCarousel {
  --f-carousel-spacing: 10px;
  --f-carousel-slides-per-page: 4;
  --f-carousel-slide-width: calc( ( 100% - ((var(--f-carousel-slides-per-page) - 1) * var(--f-carousel-spacing)) ) / var(--f-carousel-slides-per-page) );
}
```
https://jsfiddle.net/de0vu9yz/
