### ISSUE TITLE
Option to position(eg. topRight, topBottom, bottomRight, leftCenter etc.) the fancybox.

### ISSUE THREAD

**Issue by testtwf** [fancyapps/ui#599]
### Is your feature request related to a problem? Please describe.

I wanted to align the fancybox to different position based on requirement but option is not available so requesting a feature.

### Describe the solution you'd like

Thanks for this amazing plugin and i want to suggest one feature which might be great addition to it.

I want to set the alignment of fancybox to different position based on requirement.

for example - 
- bottomRight : for aligning fancybox on the  right side when it is on the bottom
- bottomCenter : for aligning fancybox on the  center when it is on the bottom
- bottomLeft : for aligning fancybox on the  left side when it is on the bottom

similarly it can have center, left,right, topCenter,topRight  & topLeft.

it should be used like -
```js
Fancybox.bind("[data-fancybox]", {type: "iframe",preload: false,autoSize: true,width: 'auto',height: 'auto', position: 'bottomLeft'});
```

It'll be a great addition to the fancybox and would be helpful for many. i hope it gets added asap.

thank you.

### Describe alternatives you've considered

Presently i have made some workaround like this - 
```css
.has-iframe .fancybox__content, .has-map .fancybox__content, .has-pdf .fancybox__content {
            /* bottom right align */
            /* bottom: 0;
            right: 0;
            position: absolute; */

            /* bottom left align */
            /* bottom: 0;
            left: 0;
            position: absolute; */

            /* top right align */
            /* top: 0;
            right: 0;
            position: absolute; */

            /* top left align */
            /* top: 0;
            left: 0;
            position: absolute; */

            /* bottom center align */
            /* margin: 0 auto;
            bottom: 0;
            position: absolute; */

            /* left align */
            /* left: 0;
            position: absolute; */

            /* right align */
            right: 0;
            position: absolute;
        }
```

**Comment by fancyapps** [comment]
I am not sure what do you mean by "position the fancybox", but you can easily control the position of your content using CSS, see this demo - https://jsfiddle.net/crxoe0m6/

```css
.bottom-left::after {
  margin: 0;
}

.bottom-left .fancybox__content {
  align-self: flex-start;
}

.top-right::before {
  margin: 0;
}

.top-right .fancybox__content {
  align-self: flex-end;
}
```

```html
<a href="https://fancyapps.com/iframe.html" data-fancybox data-type="iframe" data-custom-class="bottom-left" data-width="200" data-height="200">
  Bottom left
</a>
<br />
<a href="https://fancyapps.com/iframe.html" data-fancybox data-type="iframe" data-custom-class="top-right" data-width="200" data-height="200">
  Top right
</a>
```
