### ISSUE TITLE
Fade-in animation jump when backdrop opacity != 1

### ISSUE THREAD

**Issue by kinglozzer** [fancyapps/ui#674]
### Describe the bug

With an opacity that’s not `1`, when opening Fancybox, the backdrop fades in from `0` opacity to `1`, then jumps back to e.g. `0.5` after the animation is complete.

### Reproduction

Set an opacity that’s not `1`, e.g.:

```css
.fancybox__container {
    --fancybox-opacity: 0.5;
}
```

Open fancybox - I’m using HTML, I assume it would be the same for other media types.

### Additional context

The workaround I’m using is to create a variant of the `f-fadeIn` animation that uses the opacity variable:

```css
@keyframes f-fadeInBackdrop {
    0% {
        opacity: 0
    }
    100% {
        opacity: var(--fancybox-opacity, 1)
    }
}

.fancybox__container.is-animated[aria-hidden=false] .fancybox__backdrop {
    animation: var(--f-backdrop-enter-duration, 0.35s) ease backwards f-fadeInBackdrop;
}
```

**Comment by fancyapps** [comment]
Hi,

If you want to change the opacity of the backdrop element, you must set it using a color, example:

```css
.fancybox__container {
  --fancybox-bg: rgba(0, 0, 0, 0.5);
}
```
