### ISSUE TITLE
Vanilla CSS rather than SCSS, important for Shopify users

### ISSUE THREAD

**Issue by heyjonmanning** [fancyapps/ui#99]
jQuery is no longer required with fancyapps ui, which is great!

Would be even better if there was also a vanilla css option. 
Is this something you're working on or will consider?

SCSS is deprecated for Shopify and they now recommend only using vanilla CSS, so this rules out a lot of users from being able to fully embrace this.

**Comment by fancyapps** [comment]
Hi,

1) You can find compiled CSS files into `dist` folder.
2) This project mixes SCSS variables with CSS variables, therefore you can easily customize without using Sass, for example:

```css
.fancybox__container {
  flex-direction: column-reverse;

  --fancybox-color: #0d0c22;
  --fancybox-bg: #fff;

  --fancybox-thumbs-width: 80px;
  --fancybox-thumbs-ratio: 4 / 3;

  --carousel-button-bg: #f3f3f4;
  --carousel-button-border-radius: 8px;

  --carousel-button-svg-width: 20px;
  --carousel-button-svg-height: 20px;

  --carousel-button-svg-stroke-width: 1.5;
  --carousel-button-svg-filter: none;
}
```

(From this demo - https://fancyapps.com/playground/vj)
